### ISSUE TITLE
message.token can send bot token

### ISSUE THREAD

**Issue by tat2008** [Folody-Team/Discial#22]
I accidentally try for bot to send token using this library and it sent real, no hide bot token
![Screenshot 2022-11-07 213438](https://user-images.githubusercontent.com/89330994/200336220-6c38833f-b61a-427a-8cd6-83625ed45ca6.jpg)

**Comment by phatdev12** [comment]
> I accidentally try for bot to send token using this library and it sent real, no hide bot token ![Screenshot 2022-11-07 213438](https://user-images.githubusercontent.com/89330994/200336220-6c38833f-b61a-427a-8cd6-83625ed45ca6.jpg)

Sorry for this we will fix it now. Thank you for submitting to us about an issue you or anyone else may be experiencing. We appreciate you for these small actions.

**Comment by phatdev12** [comment]
Just **Fixed!**

**Comment by phatdev12** [comment]
Just **fixed**
